### ISSUE TITLE
will you use SST-omega turbulence model 

### ISSUE THREAD

**Issue by Leeyan007** [traviscarrigan/OpenFOAM-2D-VAWT#1]
Hello ,thank you for your generous to share your cases to us.  i'm very interested in the field of vertical wind turbine and vertical tidal turbine CFD simulation. But now i have some problems to solve.One problem is to choose appropriate k nut omega numbers of fluid field and boundarys(especially blades),(when i use SST-omega turbulence model). The second question is you used the "fixedValue (0 0 0) " type for the blades of VAWT in U(0) file .Can you tell the difference of "fixedValue (0 0 0)" and "MovingWallVelocity ( 0  0  0)"?

**Comment by traviscarrigan** [comment]
This is a dynamic mesh case (moving mesh). The fixedValue (0 0 0) is the viscous wall boundary condition. If you look in the constant directory you'll notice there is a dynamic mesh dictionary that defines the motion of the inner domain containing the blades.
